export const products = [
  {
    id: "1",
    name: "Ethereal Bloom",
    description: "A light, floral scent with notes of jasmine and rose.",
    price: 149.0,
    category: "For Her",
    scentProfile: "Floral",
    intensity: "Medium",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=800&auto=format&fit=crop",
    isNew: true,
  },
  {
    id: "2",
    name: "Midnight Oak",
    description: "Deep, woody notes with a hint of spiced vanilla.",
    price: 189.0,
    category: "For Him",
    scentProfile: "Woody",
    intensity: "High",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=800&auto=format&fit=crop",
    isNew: false,
  },
  {
    id: "3",
    name: "Suhain Signature No. 1",
    description: "Our master perfumer's private blend. Rare and captivating.",
    price: 299.0,
    category: "Signature",
    scentProfile: "Oriental",
    intensity: "Extreme",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=800&auto=format&fit=crop",
    isNew: true,
  },
  {
    id: "4",
    name: "Velvet Amber",
    description: "Warm amber infused with citrus top notes.",
    price: 159.0,
    category: "Unisex",
    scentProfile: "Spicy",
    intensity: "Medium",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=800&auto=format&fit=crop",
    isNew: false,
  },
  {
    id: "5",
    name: "Oceanic Mist",
    description: "Fresh sea salt and crisp ozone.",
    price: 129.0,
    category: "Unisex",
    scentProfile: "Fresh",
    intensity: "Light",
    image: "https://images.unsplash.com/photo-1512568433582-119bf549469d?q=80&w=800&auto=format&fit=crop",
    isNew: false,
  },
  {
    id: "6",
    name: "Royal Oud",
    description: "The gold standard of oud fragrances. Intense and regal.",
    price: 349.0,
    category: "Signature",
    scentProfile: "Oud",
    intensity: "Extreme",
    image: "https://images.unsplash.com/photo-1583445013765-d3c21d722f4b?q=80&w=800&auto=format&fit=crop",
    isNew: true,
  }
];
